audero_showphoto_application:
    resource: "@AuderoShowphotoBundle/Controller/ApplicationController.php"
    type:     annotation

audero_showphoto_interpretation:
    resource: "@AuderoShowphotoBundle/Controller/InterpretationController.php"
    type:     annotation

audero_showphoto_judgement:
    resource: "@AuderoShowphotoBundle/Controller/JudgementController.php"
    type:     annotation

audero_showphoto_game:
    resource: "@AuderoShowphotoBundle/Controller/GameController.php"
    type:     annotation

