audero_showphoto_application:
    resource: "@AuderoShowphotoBundle/Controller/ApplicationController.php"
    type:     annotation

audero_showphoto_response:
    resource: "@AuderoShowphotoBundle/Controller/PhotoResponseController.php"
    type:     annotation

audero_showphoto_judgement:
    resource: "@AuderoShowphotoBundle/Controller/JudgementController.php"
    type:     annotation

audero_showphoto_game:
    resource: "@AuderoShowphotoBundle/Controller/GameController.php"
    type:     annotation

