services:
    token.provider:
        class:  Audero\ShowphotoBundle\Uploader\Token
        arguments: ["%imgur_client_id%", "%imgur_client_secret%", "%imgur_refresh_token%"]
    photo.uploader:
        class:  Audero\ShowphotoBundle\Uploader\Uploader
        arguments: ["@token.provider"]
