services:
    rating.listener:
        class: Audero\ShowphotoBundle\EventListener\RatingUpdater
        tags:
            - { name: doctrine.event_listener, event: onFlush }
   # rating.listener:
    #  class: Audero\ShowphotoBundle\Listener\RatingListener
      #arguments: [ @service_container ]
    #  tags:
     #   - { name: kernel.event_listener, event: rate.photo, method: onRate }
    #Uploader services
    uploader.token.provider:
        class:  Audero\ShowphotoBundle\Services\Uploader\TokenProvider
        arguments: ["%imgur_client_id%", "%imgur_client_secret%", "%imgur_refresh_token%"]
        public: false;
    uploader:
        class:  Audero\ShowphotoBundle\Services\Uploader\Imgur
        arguments: ["@uploader.token.provider"]
    #Game services
    game.photo.request:
        class:  Audero\ShowphotoBundle\Services\Game\PhotoRequest
        arguments: ["@doctrine.orm.entity_manager"]
    game.photo.response:
        class:  Audero\ShowphotoBundle\Services\Game\PhotoResponse
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", "@uploader", "@security.context"]
    game.winner.queue:
        class:  Audero\ShowphotoBundle\Services\Game\WinnerQueue
        arguments: ["@doctrine.orm.entity_manager"]
    game.player.manager:
        class:  Audero\ShowphotoBundle\Services\Game\PlayerManager
        arguments: ["@doctrine.orm.entity_manager"]
    game.manager:
        class:  Audero\ShowphotoBundle\Services\Game\Manager
        arguments: ["@doctrine.orm.entity_manager", "@game.photo.request", "@game.player.manager"]