services:
    audero.uploader.token:
        class:  Audero\ShowphotoBundle\Uploader\Token
        arguments: ["%imgur_client_id%", "%imgur_client_secret%", "%imgur_refresh_token%"]
    audero.uploader:
        class:  Audero\ShowphotoBundle\Uploader\Uploader
        arguments: ["@audero.uploader.token"]
