services:
    #Uploader services
    uploader.token.provider:
        class:  Audero\ShowphotoBundle\Services\Uploader\TokenProvider
        arguments: ["%imgur_client_id%", "%imgur_client_secret%", "%imgur_refresh_token%"]
        public: false;
    uploader:
        class:  Audero\ShowphotoBundle\Services\Uploader\Imgur
        arguments: ["@uploader.token.provider"]
    #Game services
    game.request.provider:
        class:  Audero\ShowphotoBundle\Services\Game\RequestProvider
        arguments: ["@doctrine.orm.entity_manager"]
    game.winner.queue:
        class:  Audero\ShowphotoBundle\Services\Game\WinnerQueue
        arguments: ["@doctrine.orm.entity_manager"]
    game.manager:
        class:  Audero\ShowphotoBundle\Services\Game\Manager
        arguments: ["@doctrine.orm.entity_manager", "@game.request.provider"]
    game.player.manager:
        class:  Audero\ShowphotoBundle\Services\Game\PlayerManager
        arguments: ["@doctrine.orm.entity_manager"]