services:
    socket.connection.manager:
        class:  Audero\WebBundle\Services\SocketConnectionManager
        arguments: ["@doctrine.orm.entity_manager"]
    pusher:
        class:  Audero\WebBundle\Services\Pusher
        arguments: ["@socket.connection.manager"]
