imports:
  - { resource: "@AuderoBackendBundle/Resources/config/services.yml" }
  - { resource: "@AuderoShowphotoBundle/Resources/config/services.yml" }
  - { resource: "@AuderoWebBundle/Resources/config/services.yml" }

services:
  pdo:
      class: PDO
      arguments:
          dsn:      "mysql:dbname=%database_name%"
          user:     "%database_user%"
          password: "%database_password%"
      calls:
          - [setAttribute, [3, 2]] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION
  session.handler.pdo:
      class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
      arguments: ["@pdo", "%pdo.db_options%"]
  get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        tags:
           - { name: serializer.normalizer }