<?php

namespace Audero\ShowphotoBundle\Repository;

use Audero\ShowphotoBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * PhotoRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRequestRepository extends EntityRepository
{
    public function findLastBroadcasted()
    {
        return $this->getEntityManager()
            ->createQuery('
              SELECT r
              FROM AuderoShowphotoBundle:PhotoRequest r
              WHERE r.validUntil IS NOT NULL
              ORDER BY r.date DESC')
            ->setMaxResults(1)
            ->getOneOrNullResult();
    }

    public function findOneBySlug($slug)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT r FROM AuderoShowphotoBundle:PhotoRequest r WHERE r.slug = ?1')
            ->setParameter(1, $slug)
            ->getOneOrNullResult();
    }

    public function findLatest(User $user, $size) {
        return $this->getEntityManager()
            ->createQuery("SELECT req
                           FROM AuderoShowphotoBundle:PhotoRequest req
                           WHERE req.user = ?1 AND req.validUntil IS NOT NULL
                           ORDER BY req.date DESC")
            ->setMaxResults($size)
            ->setParameter(1, $user)
            ->getResult();
    }

    public function findAllData() {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT r
                 FROM AuderoShowphotoBundle:PhotoRequest r'
            )
            ->getArrayResult();

    }
}