<?php

namespace Audero\ShowphotoBundle\Repository;

use Audero\ShowphotoBundle\Entity\PhotoRequest;
use Audero\ShowphotoBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * PhotoResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoResponseRepository extends EntityRepository
{
    /**
     * @param PhotoRequest $request
     * @return array
     */
    public function findBestResponses(PhotoRequest $request) {
        $result = $this->getEntityManager()
            ->createQuery("SELECT res as response, SUM(res.likes - res.dislikes) as rating
                           FROM AuderoShowphotoBundle:PhotoResponse res
                           WHERE res.request = ?1
                           ORDER BY rating")
            ->setParameter(1, $request)
            ->getResult();

            return isset($result[0]['rating']) && !is_null($result[0]['rating']) ? $result : array();
    }

    public function findNewestWithOffset($offset, $size) {
        return $this->getEntityManager()
            ->createQuery("SELECT res
                           FROM AuderoShowphotoBundle:PhotoResponse res
                           ORDER BY res.date DESC")
            ->setFirstResult($offset)
            ->setMaxResults($size)
            ->getResult();
    }

    public function findBestWithOffset($offset, $size) {
        return $this->getEntityManager()
            ->createQuery("SELECT res
                           FROM AuderoShowphotoBundle:PhotoResponse res
                           ORDER BY res.likes - res.dislikes DESC")
            ->setFirstResult($offset)
            ->setMaxResults($size)
            ->getResult();
    }

    public function findLatest(User $user, $size) {
        return $this->getEntityManager()
            ->createQuery("SELECT res
                           FROM AuderoShowphotoBundle:PhotoResponse res
                           WHERE res.user = ?1
                           ORDER BY res.date DESC")
            ->setMaxResults($size)
            ->setParameter(1, $user)
            ->getResult();
    }

    public function findAllData() {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT r
                 FROM AuderoShowphotoBundle:PhotoResponse r'
            )
            ->getArrayResult();

    }
}
