<?php

namespace Audero\ShowphotoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PhotoRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRequestRepository extends EntityRepository
{
    public function findAllOrderedByName()
    {
/*        return $this->getEntityManager()
            ->createQuery('SELECT p FROM symBundle:Register p ORDER BY p.name ASC')
            ->getResult();*/
    }
}
