<?php

namespace Audero\ShowphotoBundle\Repository;

use Audero\ShowphotoBundle\Entity\PhotoRequest;
use Doctrine\ORM\EntityRepository;

/**
 * PhotoResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoResponseRepository extends EntityRepository
{

    /**
     * @param PhotoRequest $request
     * @return array
     */
    public function findBest(PhotoRequest $request) {
        $result = $this->getEntityManager()
            ->createQuery("SELECT res AS response, SUM(CASE WHEN rat.rate = 1 THEN 1 ELSE -1 END) AS rating
                           FROM AuderoShowphotoBundle:PhotoResponse res
                           JOIN res.ratings rat
                           WHERE res.request = ?1
                           ORDER BY rating, res.date")
            ->setParameter(1, $request)
            ->getResult();

            // TODO FIX THIS
            return !is_null($result[0]['rating']) ? $result : null;
    }

    public function findByRequest(PhotoRequest $request) {
        return $this->getEntityManager()
            ->createQuery("SELECT res
                           FROM AuderoShowphotoBundle:PhotoResponse res
                           JOIN res.ratings rat
                           WHERE res.request = ?1
                           ORDER BY res.date DESC")
            ->setParameter(1, $request)
            ->getResult();
    }
}
