<?php

namespace Audero\ShowphotoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
    public function getPlayersCount() {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT count(p) FROM AuderoShowphotoBundle:Player p'
            )
            ->getResult()[0][1];
    }

    public function findAllOrderedByRate() {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                FROM AuderoShowphotoBundle:Player p JOIN p.user u
                ORDER BY u.rate DESC'
            )
            ->getResult();
    }

    public function findWinnerQueue($request) {
        $result = $this->getEntityManager()
            ->createQuery(
                'SELECT p, u.username as username, u.rate as rate, SUM(res.likes) as likes, SUM(res.dislikes) as dislikes, SUM(res.likes - res.dislikes) resRate
                FROM AuderoShowphotoBundle:Player p JOIN p.user u JOIN u.responses res
                WHERE res.request = ?1
                ORDER BY resRate DESC'
            )
            ->setParameter(1, $request)
            ->getResult();

        return isset($result[0]['resRate']) && !is_null($result[0]['resRate']) ? $result : array();
    }
}
