<?php

namespace Audero\ShowphotoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
    public function getPlayersCount() {
        // TODO wtf ?
        return $this->getEntityManager()
            ->createQuery(
                'SELECT count(p) FROM AuderoShowphotoBundle:Player p'
            )
            ->getResult()[0][1];
    }

    public function findOrderedByRank() {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT count(p) FROM AuderoShowphotoBundle:Player p'
            )
            ->getResult()[0][1];
    }
}
