<?php

namespace Audero\ShowphotoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokenRepository extends EntityRepository
{
    public function findNewest()
    {
        return $this->getEntityManager()
            ->createQuery('
              SELECT t
              FROM AuderoShowphotoBundle:Token t
              ORDER BY t.expiresIn DESC')
            ->setMaxResults(1)
            ->getOneOrNullResult();
    }

}