<?php

namespace Audero\ShowphotoBundle\Repository;

use Audero\ShowphotoBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getRank(User $user) {
        $result = $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(u)
                 FROM AuderoShowphotoBundle:User u
                 WHERE u.rate > ?1'
            )
            ->setParameter(1, $user->getRate())
            ->getResult();

        return $result[0][1] + 1;
    }

    public function findAllData() {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT u
                 FROM AuderoShowphotoBundle:User u'
            )
            ->getArrayResult();

    }
}
