<?php

namespace Audero\ShowphotoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WinRepository extends EntityRepository
{
    public function getLastWinner() {
        $win =  $this->getEntityManager()
            ->createQuery(
                'SELECT w FROM AuderoShowphotoBundle:Win w ORDER BY w.date ASC'
            )
            ->setMaxResults(1)
            ->getResult();

        return $win ? $win[0] : null;
    }
}
