<?php

namespace Audero\ShowphotoBundle\Repository;

use Audero\ShowphotoBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * WishRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishRepository extends EntityRepository
{
    public function findUserFirstWish(User $user) {
        if(is_object($user)) {
             $result = $this->getEntityManager()
                        ->createQueryBuilder()
                            ->select('wish')
                            ->from('AuderoShowphotoBundle:Wish', 'wish')
                            ->where('wish.user = ?1')
                            ->orderBy('wish.position')
                            ->setParameter(1, $user->getId())
                            ->setMaxResults(1)
                        ->getQuery()
                        ->getResult();

            if($result) {
                return $result[0];
            }
        }

        return null;
    }
}
