<?php

namespace Audero\ShowphotoBundle\Repository;

use Audero\ShowphotoBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * WishRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishRepository extends EntityRepository
{
    public function findUserFirstWish(User $user) {
        return $this->getEntityManager()
            ->createQuery('SELECT wish FROM AuderoShowphotoBundle:Wish wish WHERE wish.user = ?1 ORDER BY wish.position ASC')
            ->setMaxResults(1)
            ->setParameter(1, $user)
            ->getOneOrNullResult();
    }
}
