backend_index:
    path: /admin
    defaults: { _controller: AuderoBackendBundle:Dashboard:index }

audero_user_index:
    path:     /admin/users
    defaults: { _controller: AuderoBackendBundle:User:index }

audero_backend_application:
    resource: "@AuderoBackendBundle/Controller/ApplicationController.php"
    type:     annotation

audero_backend_options:
    resource: "@AuderoBackendBundle/Controller/OptionsController.php"
    type:     annotation

