audero_dashboard_index:
    path: /admin
    defaults: { _controller: AuderoBackendBundle:Dashboard:index }

audero_user_index:
    path:     /admin/users
    defaults: { _controller: AuderoBackendBundle:User:index }
