backend_user:
    resource: "@AuderoBackendBundle/Controller/UserController.php"
    type:     annotation
backend_options:
    resource: "@AuderoBackendBundle/Controller/OptionsController.php"
    type:     annotation


