<?php

namespace Audero\WebBundle\Repository;

use Audero\WebBundle\Entity\UserConnection;
use Audero\WebBundle\Entity\UserSubscription;
use Doctrine\ORM\EntityRepository;

/**
 * UserSubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSubscriptionRepository extends EntityRepository
{
    public function removeSubscriptions(UserConnection $conn, $topic) {
        return $this->getEntityManager()
            ->createQuery('DELETE FROM AuderoWebBundle:UserSubscription sub WHERE sub.connection = ?1 AND sub.topic = ?2')
            ->setParameter(1, $conn)
            ->setParameter(2, $topic)
            ->getResult();
    }
}
