<?php

namespace Audero\WebBundle\Repository;

use Audero\WebBundle\Entity\UserConnection;
use Doctrine\ORM\EntityRepository;

/**
 * UserConnectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserConnectionRepository extends EntityRepository
{
    public function removeConnection(UserConnection $conn) {
        return $this->getEntityManager()
            ->createQuery('DELETE FROM AuderoWebBundle:UserConnection conn')
            ->execute();
    }
}
